REM
REM  Visual Basic Import Declarations for the SCANLAB SCANalone4-DLL
REM

Declare Function scanalone_count_cards Lib "SCANalone4.DLL" () As UShort
Declare Sub      select_rtc Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      writemem Lib "SCANalone4.DLL" (ByVal bn As UShort, ByVal adr As Integer, ByVal n As UShort, ByRef memptr As UShort)
Declare Sub      readmem Lib "SCANalone4.DLL" (ByVal bn As UShort, ByVal adr As Integer, ByVal n As UShort, ByRef memptr As UShort)
Declare Function n_usb_status Lib "SCANalone4.DLL" (ByVal n As UShort) As Integer
Declare Function usb_status Lib "SCANalone4.DLL" () As Integer
Declare Function n_load_correction_file Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal filename As String, ByVal cortable As Short, ByVal kx As Double, ByVal ky As Double, ByVal phi As Double, ByVal xoffset As Double, ByVal yoffset As Double) As Short
Declare Function load_correction_file Lib "SCANalone4.DLL" (ByVal filename As String, ByVal cortable As Short, ByVal kx As Double, ByVal ky As Double, ByVal phi As Double, ByVal xoffset As Double, ByVal yoffset As Double) As Short
Declare Function n_load_cor Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal filename As String) As Short
Declare Function load_cor Lib "SCANalone4.DLL" (ByVal filename As String) As Short
Declare Function n_load_program_file Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal name As String) As Short
Declare Function load_program_file Lib "SCANalone4.DLL" (ByVal name As String) As Short
Declare Function n_load_pro Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal filename As String) As Short
Declare Function load_pro Lib "SCANalone4.DLL" (ByVal filename As String) As Short
Declare Function n_load_varpolydelay Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal stbfilename As String, ByVal tableno As UShort) As Short
Declare Function load_varpolydelay Lib "SCANalone4.DLL" (ByVal stbfilename As String, ByVal tableno As UShort) As Short
Declare Function n_load_z_table Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal a As Double, ByVal b As Double, ByVal c As Double) As Short
Declare Function load_z_table Lib "SCANalone4.DLL" (ByVal a As Double, ByVal b As Double, ByVal c As Double) As Short
Declare Sub      n_get_waveform Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal channel As UShort, ByVal stopp As UShort, ByVal memptr As Short)
Declare Sub      get_waveform Lib "SCANalone4.DLL" (ByVal channel As UShort, ByVal stopp As UShort, ByVal memptr As Short)
Declare Sub      n_get_status Lib "SCANalone4.DLL" (ByVal n As UShort, ByRef busy As UShort, ByRef position As Integer)
Declare Sub      get_status Lib "SCANalone4.DLL" (ByRef busy As UShort, ByRef position As Integer)
Declare Function n_read_status Lib "SCANalone4.DLL" (ByVal n As UShort) As UShort
Declare Function read_status Lib "SCANalone4.DLL" () As UShort
Declare Function get_dll_version Lib "SCANalone4.DLL" () As UShort
Declare Function n_get_input_pointer Lib "SCANalone4.DLL" (ByVal n As UShort) As Integer
Declare Function get_input_pointer Lib "SCANalone4.DLL" () As Integer
Declare Sub      n_set_input_pointer Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal pointer As Integer)
Declare Sub      set_input_pointer Lib "SCANalone4.DLL" (ByVal pointer As Integer)
Declare Sub      n_set_start_list_1 Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      set_start_list_1 Lib "SCANalone4.DLL" ()
Declare Sub      n_set_start_list_2 Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      set_start_list_2 Lib "SCANalone4.DLL" ()
Declare Sub      n_set_start_list Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal listno As UShort)
Declare Sub      set_start_list Lib "SCANalone4.DLL" (ByVal listno As UShort)
Declare Sub      n_execute_list_1 Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      execute_list_1 Lib "SCANalone4.DLL" ()
Declare Sub      n_execute_list_2 Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      execute_list_2 Lib "SCANalone4.DLL" ()
Declare Sub      n_execute_list Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal listno As UShort)
Declare Sub      execute_list Lib "SCANalone4.DLL" (ByVal listno As UShort)
Declare Sub      n_write_8bit_port Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal value As UShort)
Declare Sub      write_8bit_port Lib "SCANalone4.DLL" (ByVal value As UShort)
Declare Sub      n_write_io_port Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal value As UShort)
Declare Sub      write_io_port Lib "SCANalone4.DLL" (ByVal value As UShort)
Declare Sub      n_auto_change Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      auto_change Lib "SCANalone4.DLL" ()
Declare Sub      n_aut_change Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      aut_change Lib "SCANalone4.DLL" ()
Declare Sub      n_start_loop Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      start_loop Lib "SCANalone4.DLL" ()
Declare Sub      n_quit_loop Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      quit_loop Lib "SCANalone4.DLL" ()
Declare Sub      n_stop_execution Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      stop_execution Lib "SCANalone4.DLL" ()
Declare Sub      n_dsp_start Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      dsp_start Lib "SCANalone4.DLL" ()
Declare Function n_read_io_port Lib "SCANalone4.DLL" (ByVal n As UShort) As UShort
Declare Function read_io_port Lib "SCANalone4.DLL" () As UShort
Declare Sub      n_write_da_1 Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal value As UShort)
Declare Sub      write_da_1 Lib "SCANalone4.DLL" (ByVal value As UShort)
Declare Sub      n_write_da_2 Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal value As UShort)
Declare Sub      write_da_2 Lib "SCANalone4.DLL" (ByVal value As UShort)
Declare Sub      n_write_da_x Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal x As UShort, ByVal value As UShort)
Declare Sub      write_da_x Lib "SCANalone4.DLL" (ByVal x As UShort, ByVal value As UShort)
Declare Sub      n_set_max_counts Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal counts As Integer)
Declare Sub      set_max_counts Lib "SCANalone4.DLL" (ByVal counts As Integer)
Declare Function n_get_counts Lib "SCANalone4.DLL" (ByVal n As UShort) As Integer
Declare Function get_counts Lib "SCANalone4.DLL" () As Integer
Declare Sub      n_set_matrix Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal m11 As Double, ByVal m12 As Double, ByVal m21 As Double, ByVal m22 As Double)
Declare Sub      set_matrix Lib "SCANalone4.DLL" (ByVal m11 As Double, ByVal m12 As Double, ByVal m21 As Double, ByVal m22 As Double)
Declare Sub      n_set_offset Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal xoffset As Short, ByVal yoffset As Short)
Declare Sub      set_offset Lib "SCANalone4.DLL" (ByVal xoffset As Short, ByVal yoffset As Short)
Declare Sub      n_goto_xy Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal x As Short, ByVal y As Short)
Declare Sub      goto_xy Lib "SCANalone4.DLL" (ByVal x As Short, ByVal y As Short)
Declare Sub      n_goto_xyz Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal x As Short, ByVal y As Short, ByVal z As Short)
Declare Sub      goto_xyz Lib "SCANalone4.DLL" (ByVal x As Short, ByVal y As Short, ByVal z As Short)
Declare Function n_get_hex_version Lib "SCANalone4.DLL" (ByVal n As UShort) As UShort
Declare Function get_hex_version Lib "SCANalone4.DLL" () As UShort
Declare Sub      n_enable_laser Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      enable_laser Lib "SCANalone4.DLL" ()
Declare Sub      n_disable_laser Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      disable_laser Lib "SCANalone4.DLL" ()
Declare Sub      n_stop_list Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      stop_list Lib "SCANalone4.DLL" ()
Declare Sub      n_restart_list Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      restart_list Lib "SCANalone4.DLL" ()
Declare Function n_get_rtc_version Lib "SCANalone4.DLL" (ByVal n As UShort) As UShort
Declare Function get_rtc_version Lib "SCANalone4.DLL" () As UShort
Declare Sub      n_get_xy_pos Lib "SCANalone4.DLL" (ByVal n As UShort, ByRef x As Short, ByRef y As Short)
Declare Sub      get_xy_pos Lib "SCANalone4.DLL" (ByRef x As Short, ByRef y As Short)
Declare Sub      n_get_xyz_pos Lib "SCANalone4.DLL" (ByVal n As UShort, ByRef x As Short, ByRef y As Short, ByRef z As Short)
Declare Sub      get_xyz_pos Lib "SCANalone4.DLL" (ByRef x As Short, ByRef y As Short, ByRef z As Short)
Declare Sub      n_select_list Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal list_2 As UShort)
Declare Sub      select_list Lib "SCANalone4.DLL" (ByVal list_2 As UShort)
Declare Sub      n_set_extstartpos Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal position As Integer)
Declare Sub      set_extstartpos Lib "SCANalone4.DLL" (ByVal position As Integer)
Declare Sub      n_z_out Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal z As Short)
Declare Sub      z_out Lib "SCANalone4.DLL" (ByVal z As Short)
Declare Sub      n_set_firstpulse_killer Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal fpk As UShort)
Declare Sub      set_firstpulse_killer Lib "SCANalone4.DLL" (ByVal fpk As UShort)
Declare Sub      n_set_standby Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal half_period As UShort, ByVal pulse As UShort)
Declare Sub      set_standby Lib "SCANalone4.DLL" (ByVal half_period As UShort, ByVal pulse As UShort)
Declare Sub      n_laser_signal_on Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      laser_signal_on Lib "SCANalone4.DLL" ()
Declare Sub      n_laser_signal_off Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      laser_signal_off Lib "SCANalone4.DLL" ()
Declare Sub      n_set_delay_mode Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal varpoly As UShort, ByVal directmove3d As UShort, ByVal edgelevel As UShort, ByVal minjumpdelay As UShort, ByVal jumplengthlimit As UShort)
Declare Sub      set_delay_mode Lib "SCANalone4.DLL" (ByVal varpoly As UShort, ByVal directmove3d As UShort, ByVal edgelevel As UShort, ByVal minjumpdelay As UShort, ByVal jumplengthlimit As UShort)
Declare Sub      n_set_piso_control Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal l1 As UShort, ByVal l2 As UShort)
Declare Sub      set_piso_control Lib "SCANalone4.DLL" (ByVal l1 As UShort, ByVal l2 As UShort)
Declare Sub      n_select_status Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal mode As UShort)
Declare Sub      select_status Lib "SCANalone4.DLL" (ByVal mode As UShort)
Declare Sub      n_get_encoder Lib "SCANalone4.DLL" (ByVal n As UShort, ByRef zx As Short, ByRef zy As Short)
Declare Sub      get_encoder Lib "SCANalone4.DLL" (ByRef zx As Short, ByRef zy As Short)
Declare Sub      n_select_cor_table Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal heada As UShort, ByVal headb As UShort)
Declare Sub      select_cor_table Lib "SCANalone4.DLL" (ByVal heada As UShort, ByVal headb As UShort)
Declare Sub      n_execute_at_pointer Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal position As Integer)
Declare Sub      execute_at_pointer Lib "SCANalone4.DLL" (ByVal position As Integer)
Declare Function n_get_head_status Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal head As UShort) As UShort
Declare Function get_head_status Lib "SCANalone4.DLL" (ByVal head As UShort) As UShort
Declare Sub      n_simulate_encoder Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal channel As UShort)
Declare Sub      simulate_encoder Lib "SCANalone4.DLL" (ByVal channel As UShort)
Declare Sub      n_release_wait Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      release_wait Lib "SCANalone4.DLL" ()
Declare Function n_get_wait_status Lib "SCANalone4.DLL" (ByVal n As UShort) As UShort
Declare Function get_wait_status Lib "SCANalone4.DLL" () As UShort
Declare Sub      n_set_control_mode Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal mode As UShort)
Declare Sub      set_control_mode Lib "SCANalone4.DLL" (ByVal mode As UShort)
Declare Sub      n_set_laser_mode Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal mode As UShort)
Declare Sub      set_laser_mode Lib "SCANalone4.DLL" (ByVal mode As UShort)
Declare Sub      n_set_ext_start_delay Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal delay As Short, ByVal encoder As Short)
Declare Sub      set_ext_start_delay Lib "SCANalone4.DLL" (ByVal delay As Short, ByVal encoder As Short)
Declare Sub      n_home_position Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal xhome As Short, ByVal yhome As Short)
Declare Sub      home_position Lib "SCANalone4.DLL" (ByVal xhome As Short, ByVal yhome As Short)
Declare Function n_read_ad_x Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal x As UShort) As UShort
Declare Function read_ad_x Lib "SCANalone4.DLL" (ByVal x As UShort) As UShort
Declare Function n_get_z_distance Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal x As Short, ByVal y As Short, ByVal z As Short) As Short
Declare Function get_z_distance Lib "SCANalone4.DLL" (ByVal x As Short, ByVal y As Short, ByVal z As Short) As Short
Declare Function n_get_startstop_info Lib "SCANalone4.DLL" (ByVal n As UShort) As UShort
Declare Function get_startstop_info Lib "SCANalone4.DLL" () As UShort
Declare Function n_get_marking_info Lib "SCANalone4.DLL" (ByVal n As UShort) As UShort
Declare Function get_marking_info Lib "SCANalone4.DLL" () As UShort
Declare Function n_get_io_status Lib "SCANalone4.DLL" (ByVal n As UShort) As UShort
Declare Function get_io_status Lib "SCANalone4.DLL" () As UShort
Declare Function n_get_time Lib "SCANalone4.DLL" (ByVal n As UShort) As Double
Declare Function get_time Lib "SCANalone4.DLL" () As Double
Declare Sub      n_set_defocus Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal value As Short)
Declare Sub      set_defocus Lib "SCANalone4.DLL" (ByVal value As Short)
Declare Sub      n_set_softstart_mode Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal mode As UShort, ByVal number As UShort, ByVal restartdelay As UShort)
Declare Sub      set_softstart_mode Lib "SCANalone4.DLL" (ByVal mode As UShort, ByVal number As UShort, ByVal restartdelay As UShort)
Declare Sub      n_set_softstart_level Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal index As UShort, ByVal level As UShort)
Declare Sub      set_softstart_level Lib "SCANalone4.DLL" (ByVal index As UShort, ByVal level As UShort)
Declare Sub      n_control_command Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal head As UShort, ByVal axis As UShort, ByVal data As UShort)
Declare Sub      control_command Lib "SCANalone4.DLL" (ByVal head As UShort, ByVal axis As UShort, ByVal data As UShort)
Declare Sub      n_set_rot_center Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal center_x As Integer, ByVal center_y As Integer)
Declare Sub      set_rot_center Lib "SCANalone4.DLL" (ByVal center_x As Integer, ByVal center_y As Integer)
Declare Sub      n_auto_change_pos Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal start As Integer)
Declare Sub      auto_change_pos Lib "SCANalone4.DLL" (ByVal start As Integer)
Declare Function n_get_value Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal signal As UShort) As Short
Declare Function get_value Lib "SCANalone4.DLL" (ByVal signal As UShort) As Short
Declare Sub      n_set_io_bit Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal mask1 As UShort)
Declare Sub      set_io_bit Lib "SCANalone4.DLL" (ByVal mask1 As UShort)
Declare Sub      n_clear_io_bit Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal mask0 As UShort)
Declare Sub      clear_io_bit Lib "SCANalone4.DLL" (ByVal mask0 As UShort)
Declare Sub      n_set_duty_cycle_table Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal index As UShort, ByVal dutycycle As UShort)
Declare Sub      set_duty_cycle_table Lib "SCANalone4.DLL" (ByVal index As UShort, ByVal dutycycle As UShort)
Declare Function n_store_on_mmc Lib "SCANalone4.DLL" (ByVal n As UShort) As Short
Declare Function store_on_mmc Lib "SCANalone4.DLL" () As Short
Declare Function n_get_serial_number Lib "SCANalone4.DLL" (ByVal n As UShort) As UShort
Declare Function get_serial_number Lib "SCANalone4.DLL" () As UShort
Declare Function n_get_serial_number_32 Lib "SCANalone4.DLL" (ByVal n As UShort) As Integer
Declare Function get_serial_number_32 Lib "SCANalone4.DLL" () As Integer
Declare Sub      n_measurement_status Lib "SCANalone4.DLL" (ByVal n As UShort, ByRef busy As UShort, ByRef position As UShort)
Declare Sub      measurement_status Lib "SCANalone4.DLL" (ByRef busy As UShort, ByRef position As UShort)
Declare Sub      n_clear_list Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      clear_list Lib "SCANalone4.DLL" ()
Declare Sub      n_set_char_table Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal ch As UShort, ByVal listpos As Integer)
Declare Sub      set_char_table Lib "SCANalone4.DLL" (ByVal ch As UShort, ByVal listpos As Integer)
Declare Sub      n_time_update Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      time_update Lib "SCANalone4.DLL" ()
Declare Sub      n_set_serial Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal no As Integer)
Declare Sub      set_serial Lib "SCANalone4.DLL" (ByVal no As Integer)
Declare Function n_memory_test Lib "SCANalone4.DLL" (ByVal n As UShort) As Integer
Declare Function memory_test Lib "SCANalone4.DLL" () As Integer
Declare Sub      n_list_nop Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      list_nop Lib "SCANalone4.DLL" ()
Declare Sub      n_set_end_of_list Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      set_end_of_list Lib "SCANalone4.DLL" ()
Declare Sub      n_jump_abs Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal x As Short, ByVal y As Short)
Declare Sub      jump_abs Lib "SCANalone4.DLL" (ByVal x As Short, ByVal y As Short)
Declare Sub      n_jump_abs_3d Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal x As Short, ByVal y As Short, ByVal z As Short)
Declare Sub      jump_abs_3d Lib "SCANalone4.DLL" (ByVal x As Short, ByVal y As Short, ByVal z As Short)
Declare Sub      n_mark_abs Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal x As Short, ByVal y As Short)
Declare Sub      mark_abs Lib "SCANalone4.DLL" (ByVal x As Short, ByVal y As Short)
Declare Sub      n_mark_abs_3d Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal x As Short, ByVal y As Short, ByVal z As Short)
Declare Sub      mark_abs_3d Lib "SCANalone4.DLL" (ByVal x As Short, ByVal y As Short, ByVal z As Short)
Declare Sub      n_jump_rel Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal dx As Short, ByVal dy As Short)
Declare Sub      jump_rel Lib "SCANalone4.DLL" (ByVal dx As Short, ByVal dy As Short)
Declare Sub      n_jump_rel_3d Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal dx As Short, ByVal dy As Short, ByVal dz As Short)
Declare Sub      jump_rel_3d Lib "SCANalone4.DLL" (ByVal dx As Short, ByVal dy As Short, ByVal dz As Short)
Declare Sub      n_mark_rel Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal dx As Short, ByVal dy As Short)
Declare Sub      mark_rel Lib "SCANalone4.DLL" (ByVal dx As Short, ByVal dy As Short)
Declare Sub      n_mark_rel_3d Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal dx As Short, ByVal dy As Short, ByVal dz As Short)
Declare Sub      mark_rel_3d Lib "SCANalone4.DLL" (ByVal dx As Short, ByVal dy As Short, ByVal dz As Short)
Declare Sub      n_write_8bit_port_list Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal value As UShort)
Declare Sub      write_8bit_port_list Lib "SCANalone4.DLL" (ByVal value As UShort)
Declare Sub      n_write_da_1_list Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal value As UShort)
Declare Sub      write_da_1_list Lib "SCANalone4.DLL" (ByVal value As UShort)
Declare Sub      n_write_da_2_list Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal value As UShort)
Declare Sub      write_da_2_list Lib "SCANalone4.DLL" (ByVal value As UShort)
Declare Sub      n_write_da_x_list Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal x As UShort, ByVal value As UShort)
Declare Sub      write_da_x_list Lib "SCANalone4.DLL" (ByVal x As UShort, ByVal value As UShort)
Declare Sub      n_set_offset_list Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal xoffset As Short, ByVal yoffset As Short)
Declare Sub      set_offset_list Lib "SCANalone4.DLL" (ByVal xoffset As Short, ByVal yoffset As Short)
Declare Sub      n_long_delay Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal value As UShort)
Declare Sub      long_delay Lib "SCANalone4.DLL" (ByVal value As UShort)
Declare Sub      n_laser_on_list Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal value As UShort)
Declare Sub      laser_on_list Lib "SCANalone4.DLL" (ByVal value As UShort)
Declare Sub      n_set_jump_speed Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal speed As Double)
Declare Sub      set_jump_speed Lib "SCANalone4.DLL" (ByVal speed As Double)
Declare Sub      n_set_mark_speed Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal speed As Double)
Declare Sub      set_mark_speed Lib "SCANalone4.DLL" (ByVal speed As Double)
Declare Sub      n_set_laser_delays Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal ondelay As Short, ByVal offdelay As Short)
Declare Sub      set_laser_delays Lib "SCANalone4.DLL" (ByVal ondelay As Short, ByVal offdelay As Short)
Declare Sub      n_set_scanner_delays Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal jumpdelay As UShort, ByVal markdelay As UShort, ByVal polydelay As UShort)
Declare Sub      set_scanner_delays Lib "SCANalone4.DLL" (ByVal jumpdelay As UShort, ByVal markdelay As UShort, ByVal polydelay As UShort)
Declare Sub      n_set_list_jump Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal position As Integer)
Declare Sub      set_list_jump Lib "SCANalone4.DLL" (ByVal position As Integer)
Declare Sub      n_list_call Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal position As Integer)
Declare Sub      list_call Lib "SCANalone4.DLL" (ByVal position As Integer)
Declare Sub      n_list_return Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      list_return Lib "SCANalone4.DLL" ()
Declare Sub      n_z_out_list Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal z As Short)
Declare Sub      z_out_list Lib "SCANalone4.DLL" (ByVal z As Short)
Declare Sub      n_set_standby_list Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal half_period As UShort, ByVal pulse As UShort)
Declare Sub      set_standby_list Lib "SCANalone4.DLL" (ByVal half_period As UShort, ByVal pulse As UShort)
Declare Sub      n_timed_jump_abs Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal x As Short, ByVal y As Short, ByVal time As Double)
Declare Sub      timed_jump_abs Lib "SCANalone4.DLL" (ByVal x As Short, ByVal y As Short, ByVal time As Double)
Declare Sub      n_timed_mark_abs Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal x As Short, ByVal y As Short, ByVal time As Double)
Declare Sub      timed_mark_abs Lib "SCANalone4.DLL" (ByVal x As Short, ByVal y As Short, ByVal time As Double)
Declare Sub      n_timed_jump_rel Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal dx As Short, ByVal dy As Short, ByVal time As Double)
Declare Sub      timed_jump_rel Lib "SCANalone4.DLL" (ByVal dx As Short, ByVal dy As Short, ByVal time As Double)
Declare Sub      n_timed_mark_rel Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal dx As Short, ByVal dy As Short, ByVal time As Double)
Declare Sub      timed_mark_rel Lib "SCANalone4.DLL" (ByVal dx As Short, ByVal dy As Short, ByVal time As Double)
Declare Sub      n_set_laser_timing Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal halfperiod As UShort, ByVal pulse1 As UShort, ByVal pulse2 As UShort, ByVal timebase As UShort)
Declare Sub      set_laser_timing Lib "SCANalone4.DLL" (ByVal halfperiod As UShort, ByVal pulse1 As UShort, ByVal pulse2 As UShort, ByVal timebase As UShort)
Declare Sub      n_set_wobbel Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal amplitude As UShort, ByVal frequency As Double)
Declare Sub      set_wobbel Lib "SCANalone4.DLL" (ByVal amplitude As UShort, ByVal frequency As Double)
Declare Sub      n_set_fly_x Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal kx As Double)
Declare Sub      set_fly_x Lib "SCANalone4.DLL" (ByVal kx As Double)
Declare Sub      n_set_fly_y Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal ky As Double)
Declare Sub      set_fly_y Lib "SCANalone4.DLL" (ByVal ky As Double)
Declare Sub      n_write_io_port_list Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal value As UShort)
Declare Sub      write_io_port_list Lib "SCANalone4.DLL" (ByVal value As UShort)
Declare Sub      n_set_wait Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal value As UShort)
Declare Sub      set_wait Lib "SCANalone4.DLL" (ByVal value As UShort)
Declare Sub      n_simulate_ext_start Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal delay As Short, ByVal encoder As Short)
Declare Sub      simulate_ext_start Lib "SCANalone4.DLL" (ByVal delay As Short, ByVal encoder As Short)
Declare Sub      n_set_pixel_line Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal pixelmode As UShort, ByVal pixelperiod As UShort, ByVal dx As Double, ByVal dy As Double)
Declare Sub      set_pixel_line Lib "SCANalone4.DLL" (ByVal pixelmode As UShort, ByVal pixelperiod As UShort, ByVal dx As Double, ByVal dy As Double)
Declare Sub      n_set_pixel Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal pulswidth As UShort, ByVal davalue As UShort, ByVal dummy As UShort)
Declare Sub      set_pixel Lib "SCANalone4.DLL" (ByVal pulswidth As UShort, ByVal davalue As UShort, ByVal dummy As UShort)
Declare Sub      n_set_extstartpos_list Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal position As Integer)
Declare Sub      set_extstartpos_list Lib "SCANalone4.DLL" (ByVal position As Integer)
Declare Sub      n_laser_signal_on_list Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      laser_signal_on_list Lib "SCANalone4.DLL" ()
Declare Sub      n_laser_signal_off_list Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      laser_signal_off_list Lib "SCANalone4.DLL" ()
Declare Sub      n_set_firstpulse_killer_list Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal fpk As UShort)
Declare Sub      set_firstpulse_killer_list Lib "SCANalone4.DLL" (ByVal fpk As UShort)
Declare Sub      n_set_io_cond_list Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal mask_1 As UShort, ByVal mask_0 As UShort, ByVal mask_set As UShort)
Declare Sub      set_io_cond_list Lib "SCANalone4.DLL" (ByVal mask_1 As UShort, ByVal mask_0 As UShort, ByVal mask_set As UShort)
Declare Sub      n_clear_io_cond_list Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal mask_1 As UShort, ByVal mask_0 As UShort, ByVal mask_clear As UShort)
Declare Sub      clear_io_cond_list Lib "SCANalone4.DLL" (ByVal mask_1 As UShort, ByVal mask_0 As UShort, ByVal mask_clear As UShort)
Declare Sub      n_list_jump_cond Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal mask_1 As UShort, ByVal mask_0 As UShort, ByVal position As Integer)
Declare Sub      list_jump_cond Lib "SCANalone4.DLL" (ByVal mask_1 As UShort, ByVal mask_0 As UShort, ByVal position As Integer)
Declare Sub      n_list_call_cond Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal mask_1 As UShort, ByVal mask_0 As UShort, ByVal position As Integer)
Declare Sub      list_call_cond Lib "SCANalone4.DLL" (ByVal mask_1 As UShort, ByVal mask_0 As UShort, ByVal position As Integer)
Declare Sub      n_save_and_restart_timer Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      save_and_restart_timer Lib "SCANalone4.DLL" ()
Declare Sub      n_set_matrix_list Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal i As UShort, ByVal j As UShort, ByVal mij As Double)
Declare Sub      set_matrix_list Lib "SCANalone4.DLL" (ByVal i As UShort, ByVal j As UShort, ByVal mij As Double)
Declare Sub      n_set_control_mode_list Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal mode As UShort)
Declare Sub      set_control_mode_list Lib "SCANalone4.DLL" (ByVal mode As UShort)
Declare Sub      n_set_defocus_list Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal value As Short)
Declare Sub      set_defocus_list Lib "SCANalone4.DLL" (ByVal value As Short)
Declare Sub      n_set_ext_start_delay_list Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal delay As Short, ByVal encoder As Short)
Declare Sub      set_ext_start_delay_list Lib "SCANalone4.DLL" (ByVal delay As Short, ByVal encoder As Short)
Declare Sub      n_set_wobbel_xy Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal long_wob As UShort, ByVal trans_wob As UShort, ByVal frequency As Double)
Declare Sub      set_wobbel_xy Lib "SCANalone4.DLL" (ByVal long_wob As UShort, ByVal trans_wob As UShort, ByVal frequency As Double)
Declare Sub      n_calculate_fly Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal direction As UShort, ByVal distance As Double)
Declare Sub      calculate_fly Lib "SCANalone4.DLL" (ByVal direction As UShort, ByVal distance As Double)
Declare Sub      n_select_cor_table_list Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal heada As UShort, ByVal headb As UShort)
Declare Sub      select_cor_table_list Lib "SCANalone4.DLL" (ByVal heada As UShort, ByVal headb As UShort)
Declare Sub      n_set_fly_rot Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal resolution As Double)
Declare Sub      set_fly_rot Lib "SCANalone4.DLL" (ByVal resolution As Double)
Declare Sub      n_fly_return Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal x As Short, ByVal y As Short)
Declare Sub      fly_return Lib "SCANalone4.DLL" (ByVal x As Short, ByVal y As Short)
Declare Sub      n_set_trigger Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal sampleperiod As UShort, ByVal channel1 As UShort, ByVal channel2 As UShort)
Declare Sub      set_trigger Lib "SCANalone4.DLL" (ByVal sampleperiod As UShort, ByVal channel1 As UShort, ByVal channel2 As UShort)
Declare Sub      n_arc_rel Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal dx As Short, ByVal dy As Short, ByVal angle As Double)
Declare Sub      arc_rel Lib "SCANalone4.DLL" (ByVal dx As Short, ByVal dy As Short, ByVal angle As Double)
Declare Sub      n_arc_abs Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal x As Short, ByVal y As Short, ByVal angle As Double)
Declare Sub      arc_abs Lib "SCANalone4.DLL" (ByVal x As Short, ByVal y As Short, ByVal angle As Double)
Declare Sub      n_time_fix Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      time_fix Lib "SCANalone4.DLL" ()
Declare Sub      n_time_fix_f Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal mode As UShort)
Declare Sub      time_fix_f Lib "SCANalone4.DLL" (ByVal mode As UShort)
Declare Sub      n_mark_time Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal part As UShort, ByVal mode As UShort)
Declare Sub      mark_time Lib "SCANalone4.DLL" (ByVal part As UShort, ByVal mode As UShort)
Declare Sub      n_mark_date Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal part As UShort, ByVal mode As UShort)
Declare Sub      mark_date Lib "SCANalone4.DLL" (ByVal part As UShort, ByVal mode As UShort)
Declare Sub      n_mark_serial Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal mode As UShort, ByVal digits As UShort)
Declare Sub      mark_serial Lib "SCANalone4.DLL" (ByVal mode As UShort, ByVal digits As UShort)
Declare Sub      n_date_check Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal month1 As UShort, ByVal month2 As UShort, ByVal month3 As UShort)
Declare Sub      date_check Lib "SCANalone4.DLL" (ByVal month1 As UShort, ByVal month2 As UShort, ByVal month3 As UShort)
Declare Sub      n_flyline Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal encoderdelay As Short)
Declare Sub      flyline Lib "SCANalone4.DLL" (ByVal encoderdelay As Short)
Declare Sub      n_drilling Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal pulsewidth As Short, ByVal relencoderdelay As Short)
Declare Sub      drilling Lib "SCANalone4.DLL" (ByVal pulsewidth As Short, ByVal relencoderdelay As Short)
Declare Sub      n_regulation Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      regulation Lib "SCANalone4.DLL" ()
Declare Sub      n_store_encoder Lib "SCANalone4.DLL" (ByVal n As UShort)
Declare Sub      store_encoder Lib "SCANalone4.DLL" ()
Declare Sub      n_fly_displacement_ret Lib "SCANalone4.DLL" (ByVal n As UShort, ByVal x As Short, ByVal y As Short)
Declare Sub      fly_displacement_ret Lib "SCANalone4.DLL" (ByVal x As Short, ByVal y As Short)
